input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "comptel-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
} 