# Ce fichier est désactivé temporairement pour debug. Renommez-le en .yml pour le réactiver.

name: Release Please Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: maven
          package-name: comptel-backend 